# Generated by Django 5.0.4 on 2024-04-04 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='step title')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='task name')),
                ('description', models.TextField(max_length=10000, verbose_name='task description')),
                ('deadline', models.DateTimeField(verbose_name='task deadline')),
                ('priority', models.CharField(choices=[('low', 'low priority'), ('medium', 'medium priority'), ('high', 'high priority'), ('urgent', 'urgent priority'), ('critical', 'critical priority')], default='low', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('authors', models.ManyToManyField(related_name='author_tasks', to=settings.AUTH_USER_MODEL)),
                ('steps', models.ManyToManyField(to='api.step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='tasks',
            field=models.ManyToManyField(to='api.task'),
        ),
    ]
