# Generated by Django 5.0.4 on 2024-06-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
    ]
