# Generated by Django 5.0.4 on 2024-04-05 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(10, message='name value has to be at least 10 symbols'), django.core.validators.MaxLengthValidator(250, message='maximum length is 250 symbols')], verbose_name='task name'),
        ),
    ]
