# Generated by Django 5.0.4 on 2024-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usercustom_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='profile_picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
