# Generated by Django 5.0.4 on 2024-04-07 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(error_messages={'required': 'Name field is required!'}, max_length=250, validators=[django.core.validators.MinLengthValidator(10, message='name value has to be at least 10 symbols'), django.core.validators.MaxLengthValidator(250, message='maximum length is 250 symbols')], verbose_name='task name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'low priority'), ('medium', 'medium priority'), ('high', 'high priority'), ('urgent', 'urgent priority'), ('critical', 'critical priority')], default='low', max_length=10),
        ),
    ]
